name: BlitzSG
version: 1.0
main: me.hardstyles.blitz.BlitzSG
depend: [KarhuAPI]
author: Syes, Hardstyles
description: BlitzSG Plugin

commands:
  fw:
    description: lol
  acban:
    description: lol
  unban:
    description: lol
  taunt:
    description: lol
  wtfmap:
    description: lol
  startdm:
    description: lolt
  test:
    description: lol
  party:
    description: lol
    aliases:
      - p
  partychat:
    aliases:
      - pc
    description: lol

