name: Core
version: 1.0
main: me.hardstyles.blitz.Core
depend: [KarhuAPI]
author: Syes, Hardstyles
description: BlitzSG Plugin

commands:
  fw:
    description: lol
  acban:
    description: lol
  unban:
    description: lol
  taunt:
    description: lol
  wtfmap:
    description: lol
  startdm:
    description: lolt
  test:
    description: lol
  party:
    description: lol
    aliases:
      - p
  partychat:
    aliases:
      - pc
    description: lol
  rank:
    description: yes
  nick:
    description: lol
  queue:
    description: x
  world:
    description: horsemeat
  rename:
    description: d
  hub:
    aliases:
      - l
      - lobby
      - spawn
      - exit
      - quit
      - leave
  spectator:
    aliases:
      - spec
      - spectate
  duel:
    aliases:
      - dual
      - 1v1
